.\" Strona podrecznika systemowego dla programu wjeszak.
.TH "WJESZAK" 1 "01 marca 2017" "Wersja 1.0"
.SH NAZWA (NAME)
\fBwjeszak\fP - testowanie bibliotek dołączanych statycznie i dynamicznie
.SH SKLADNIA (SYNOPSIS)

\fBwjeszak\fP \fIliczba\fI
.br
\fBwjeszak\fP \fIlitera\fI
.SH OPIS (DESCRIPTION)
Program przyjmuje jako argument 2 liczby z zakresu 1..100 i zwraca ich sumę.
.TP
\fB\-\-pomoc\fP
wyświetla ten tekst i kończy pracę
.TP
\fB\-\-wersja\fP
wyświetla informację o wersji i kończy pracę
.PP
Wszelkie uwagi odnośnie działania programu proszę wysyłać na <wjeszak@gmail.com>
.SH AUTOR (AUTHOR)
Napisane przez Tomasza Wieszczka.
